package io.teaql.core.reference;

public enum RoundTripReferenceErrorCode {
    PROVIDER_NOT_CONFIGURED,
    CONTEXT_BINDING_REQUIRED,
    INVALID_REFERENCE,
    EXPIRED,
    SCOPE_MISMATCH,
    AUTHORIZATION_REQUIRED,
    CONFIGURATION_INVALID,
    CONTEXT_MISMATCH,
    TYPE_MISMATCH,
    INVALID_ENTITY_IDENTITY
}
