sed -i '915,924d' /home/philip/githome/teaql-java/teaql-sql/src/main/java/io/teaql/core/sql/SQLRepository.java
sed -i '902,913d' /home/philip/githome/teaql-java/teaql-sql/src/main/java/io/teaql/core/sql/SQLRepository.java
sed -i '890,892d' /home/philip/githome/teaql-java/teaql-sql/src/main/java/io/teaql/core/sql/SQLRepository.java
sed -i '867,870d' /home/philip/githome/teaql-java/teaql-sql/src/main/java/io/teaql/core/sql/SQLRepository.java
sed -i '826,852d' /home/philip/githome/teaql-java/teaql-sql/src/main/java/io/teaql/core/sql/SQLRepository.java
sed -i '787,824d' /home/philip/githome/teaql-java/teaql-sql/src/main/java/io/teaql/core/sql/SQLRepository.java
sed -i '696,698d' /home/philip/githome/teaql-java/teaql-sql/src/main/java/io/teaql/core/sql/SQLRepository.java
sed -i '685,694d' /home/philip/githome/teaql-java/teaql-sql/src/main/java/io/teaql/core/sql/SQLRepository.java
sed -i '661,683d' /home/philip/githome/teaql-java/teaql-sql/src/main/java/io/teaql/core/sql/SQLRepository.java
