<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.teaql</groupId>
        <artifactId>teaql-java-parent</artifactId>
        <version>1.534-RELEASE</version>
    </parent>
    <artifactId>teaql-dm8</artifactId>
    <name>teaql-dm8</name>
    <dependencies>
        <dependency>
            <groupId>io.teaql</groupId>
            <artifactId>teaql-data-service-sql</artifactId>
        </dependency>
        <dependency>
            <groupId>io.teaql</groupId>
            <artifactId>teaql-utils</artifactId>
        </dependency>
        <!-- Testing dependencies -->
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.dameng</groupId>
            <artifactId>DmJdbcDriver18</artifactId>
            <version>8.1.3.140</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.teaql</groupId>
            <artifactId>teaql-provider-jdbc</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.teaql</groupId>
            <artifactId>teaql-runtime</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <argLine>
                        --add-reads io.teaql.dm8=io.teaql.runtime
                        --add-opens io.teaql.dm8/io.teaql.dm8=io.teaql.utils
                        --add-opens io.teaql.core/io.teaql.core=io.teaql.utils
                    </argLine>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
