package io.teaql.core.businessid;

public enum BusinessIdErrorCode {
    BUSINESS_ID_PROFILE_NOT_FOUND,
    BUSINESS_ID_DEFINITION_INVALID,
    BUSINESS_ID_RANGE_EXHAUSTED,
    BUSINESS_ID_ALLOCATION_RETRY_EXHAUSTED,
    BUSINESS_ID_FORMAT_INVALID,
    BUSINESS_ID_DUPLICATE,
    BUSINESS_ID_IMMUTABLE
}
