
spring.application.name=runtime-example-conformance-service
server.port=9987
spring.datasource.type=com.zaxxer.hikari.HikariDataSource
teaql.contextClass=com.teaql.runtimeexampleconformanceservice.CustomUserContext

spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.url=jdbc:sqlite:runtimeexampleconformanceservice.db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.data.redis.port=6379
plc.deploy.url=
card.service.url=
aliyun.sms.ak=
aliyun.sms.sk=