package io.teaql.core.sql.expression;

import java.util.Map;

import io.teaql.core.SearchCriteria;
import io.teaql.core.Parameter;
import io.teaql.core.PropertyReference;
import io.teaql.core.UserContext;
import io.teaql.core.criteria.Operator;
import io.teaql.core.criteria.TwoOperatorCriteria;
import io.teaql.core.criteria.VersionSearchCriteria;

import io.teaql.core.sql.SQLColumnResolver;
public class VersionSearchCriteriaParser implements SQLExpressionParser<VersionSearchCriteria> {
    public Class<VersionSearchCriteria> type() {
        return VersionSearchCriteria.class;
    }

    @Override
    public String toSql(
            UserContext userContext,
            VersionSearchCriteria expression,
            String idTable,
            Map<String, Object> parameters,
            SQLColumnResolver sqlColumnResolver) {
        SearchCriteria searchCriteria = expression.getSearchCriteria();
        // The active-row predicate is generated by TeaQL itself.  Inline only the
        // exact, type-checked constant; every caller-controlled value remains bound.
        if (isActiveRowPredicate(searchCriteria)) {
            TwoOperatorCriteria criteria = (TwoOperatorCriteria) searchCriteria;
            String propertySql = ExpressionHelper.toSql(
                    userContext, criteria.first(), idTable, parameters, sqlColumnResolver);
            return propertySql + " > 0";
        }
        return ExpressionHelper.toSql(
                userContext, searchCriteria, idTable, parameters, sqlColumnResolver);
    }

    private boolean isActiveRowPredicate(SearchCriteria searchCriteria) {
        if (!(searchCriteria instanceof TwoOperatorCriteria criteria)
                || criteria.getOperator() != Operator.GREATER_THAN
                || !(criteria.first() instanceof PropertyReference property)
                || !"version".equals(property.getPropertyName())
                || !(criteria.second() instanceof Parameter parameter)
                || !(parameter.getValue() instanceof Number number)) {
            return false;
        }
        return number.longValue() == 0L && number.doubleValue() == 0D;
    }
}
