<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.teaql</groupId>
        <artifactId>teaql-java-parent</artifactId>
        <version>1.533-RELEASE</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>teaql-redis</artifactId>
    <name>teaql-redis</name>
    <description>Redis based cache and lock implementation for TeaQL</description>

    <dependencies>
        <dependency>
            <groupId>io.teaql</groupId>
            <artifactId>teaql-utils</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>io.teaql</groupId>
            <artifactId>teaql-core</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>redis.clients</groupId>
            <artifactId>jedis</artifactId>
            <version>7.5.3</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.16.1</version>
        </dependency>
    </dependencies>
</project>
